//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.4952
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTXCreator.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DTXCreator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap BGMのみ再生 {
            get {
                object obj = ResourceManager.GetObject("BGMのみ再生", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   022 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DTXC_VERSION {
            get {
                return ResourceManager.GetString("DTXC_VERSION", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon dtxcreator {
            get {
                object obj = ResourceManager.GetObject("dtxcreator", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Redo {
            get {
                object obj = ResourceManager.GetObject("Redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   BPM値を設定して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strBPM選択ダイアログの説明文 {
            get {
                return ResourceManager.GetString("strBPM選択ダイアログの説明文", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DTXファイルではありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strDTXファイルではありませんMSG {
            get {
                return ResourceManager.GetString("strDTXファイルではありませんMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読み込むDTXファイルの選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strDTXファイル選択ダイアログのタイトル {
            get {
                return ResourceManager.GetString("strDTXファイル選択ダイアログのタイトル", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DTXファイル (*.dtx;*.gda;*.g2d;*.bms;*.bme)|*.dtx;*.gda;*.g2d;*.bms;*.bme|すべてのファイル(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strDTXファイル選択ダイアログのフィルタ {
            get {
                return ResourceManager.GetString("strDTXファイル選択ダイアログのフィルタ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strエラーダイアログのタイトル {
            get {
                return ResourceManager.GetString("strエラーダイアログのタイトル", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DTXCreator.config の読み込みに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strコンフィグ読み込み失敗エラーMSG {
            get {
                return ResourceManager.GetString("strコンフィグ読み込み失敗エラーMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サウンドファイルの選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strサウンドファイル選択ダイアログのタイトル {
            get {
                return ResourceManager.GetString("strサウンドファイル選択ダイアログのタイトル", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サウンドファイル(*.wav;*.ogg;*.mp3;*.xa)|*.wav;*.ogg;*.mp3;*.xa|すべてのファイル(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strサウンドファイル選択ダイアログのフィルタ {
            get {
                return ResourceManager.GetString("strサウンドファイル選択ダイアログのフィルタ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   しばらくお待ち下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strしばらくお待ち下さいMSG {
            get {
                return ResourceManager.GetString("strしばらくお待ち下さいMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loadingファイルの選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strステージ画像ファイル選択ダイアログのタイトル {
            get {
                return ResourceManager.GetString("strステージ画像ファイル選択ダイアログのタイトル", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チップ番号に誤りがあります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strチップ番号に誤りがありますMSG {
            get {
                return ResourceManager.GetString("strチップ番号に誤りがありますMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strデフォルトウィンドウタイトル {
            get {
                return ResourceManager.GetString("strデフォルトウィンドウタイトル", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルが存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strファイルが存在しませんMSG {
            get {
                return ResourceManager.GetString("strファイルが存在しませんMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選曲画像ファイルの選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strプレビュー画像ファイル選択ダイアログのタイトル {
            get {
                return ResourceManager.GetString("strプレビュー画像ファイル選択ダイアログのタイトル", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プレビュー音ファイルの選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strプレビュー音ファイル選択ダイアログのタイトル {
            get {
                return ResourceManager.GetString("strプレビュー音ファイル選択ダイアログのタイトル", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロセスの起動に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strプロセスの起動に失敗しましたMSG {
            get {
                return ResourceManager.GetString("strプロセスの起動に失敗しましたMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存中です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str保存中ですMSG {
            get {
                return ResourceManager.GetString("str保存中ですMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///    個のチップが選択されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str個のチップが選択されましたMSG {
            get {
                return ResourceManager.GetString("str個のチップが選択されましたMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///    個のチップを置換しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str個のチップを置換しましたMSG {
            get {
                return ResourceManager.GetString("str個のチップを置換しましたMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   初期化中です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str初期化中ですMSG {
            get {
                return ResourceManager.GetString("str初期化中ですMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動画ファイルの選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str動画ファイル選択ダイアログのタイトル {
            get {
                return ResourceManager.GetString("str動画ファイル選択ダイアログのタイトル", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動画ファイル(*.avi)|*.avi|すべてのファイル(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str動画ファイル選択ダイアログのフィルタ {
            get {
                return ResourceManager.GetString("str動画ファイル選択ダイアログのフィルタ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前を付けて保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str名前を付けて保存ダイアログのタイトル {
            get {
                return ResourceManager.GetString("str名前を付けて保存ダイアログのタイトル", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DTXファイル(*.dtx)|*.dtx に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str名前を付けて保存ダイアログのフィルタ {
            get {
                return ResourceManager.GetString("str名前を付けて保存ダイアログのフィルタ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   小節番号に誤りがあります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str小節番号に誤りがありますMSG {
            get {
                return ResourceManager.GetString("str小節番号に誤りがありますMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索結果 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str検索結果ダイアログのタイトル {
            get {
                return ResourceManager.GetString("str検索結果ダイアログのタイトル", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像ファイルの選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str画像ファイル選択ダイアログのタイトル {
            get {
                return ResourceManager.GetString("str画像ファイル選択ダイアログのタイトル", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像ファイル(*.bmp;*.jpg;*.jpeg;*.png)|*.bmp;*.jpg;*.jpeg;*.png|すべてのファイル(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str画像ファイル選択ダイアログのフィルタ {
            get {
                return ResourceManager.GetString("str画像ファイル選択ダイアログのフィルタ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str確認ダイアログのタイトル {
            get {
                return ResourceManager.GetString("str確認ダイアログのタイトル", resourceCulture);
            }
        }
        
        /// <summary>
        ///   結果画像ファイルの選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str結果画像ファイル選択ダイアログのタイトル {
            get {
                return ResourceManager.GetString("str結果画像ファイル選択ダイアログのタイトル", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集中のデータを保存しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str編集中のデータを保存しますかMSG {
            get {
                return ResourceManager.GetString("str編集中のデータを保存しますかMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   置換結果 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str置換結果ダイアログのタイトル {
            get {
                return ResourceManager.GetString("str置換結果ダイアログのタイトル", resourceCulture);
            }
        }
        
        /// <summary>
        ///   背景画像ファイルの選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str背景画像ファイル選択ダイアログのタイトル {
            get {
                return ResourceManager.GetString("str背景画像ファイル選択ダイアログのタイトル", resourceCulture);
            }
        }
        
        /// <summary>
        ///   該当するチップはありませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str該当するチップはありませんでしたMSG {
            get {
                return ResourceManager.GetString("str該当するチップはありませんでしたMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読み込み中です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str読み込み中ですMSG {
            get {
                return ResourceManager.GetString("str読み込み中ですMSG", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Undo {
            get {
                object obj = ResourceManager.GetObject("Undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap コピー {
            get {
                object obj = ResourceManager.GetObject("コピー", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap スピーカー {
            get {
                object obj = ResourceManager.GetObject("スピーカー", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ﾁｯﾌﾟﾊﾟﾚｯﾄ {
            get {
                object obj = ResourceManager.GetObject("ﾁｯﾌﾟﾊﾟﾚｯﾄ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap バージョン情報 {
            get {
                object obj = ResourceManager.GetObject("バージョン情報", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ヘルプ {
            get {
                object obj = ResourceManager.GetObject("ヘルプ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap りらちょー {
            get {
                object obj = ResourceManager.GetObject("りらちょー", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 上移動 {
            get {
                object obj = ResourceManager.GetObject("上移動", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 下移動 {
            get {
                object obj = ResourceManager.GetObject("下移動", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 保存 {
            get {
                object obj = ResourceManager.GetObject("保存", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 再生 {
            get {
                object obj = ResourceManager.GetObject("再生", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 再生一時停止 {
            get {
                object obj = ResourceManager.GetObject("再生一時停止", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 再生停止 {
            get {
                object obj = ResourceManager.GetObject("再生停止", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 切り取り {
            get {
                object obj = ResourceManager.GetObject("切り取り", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 削除 {
            get {
                object obj = ResourceManager.GetObject("削除", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 動画ドキュメント {
            get {
                object obj = ResourceManager.GetObject("動画ドキュメント", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 新規作成 {
            get {
                object obj = ResourceManager.GetObject("新規作成", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 最初から再生 {
            get {
                object obj = ResourceManager.GetObject("最初から再生", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 画像ドキュメント {
            get {
                object obj = ResourceManager.GetObject("画像ドキュメント", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 矢印ポインタ {
            get {
                object obj = ResourceManager.GetObject("矢印ポインタ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 表示形式選択 {
            get {
                object obj = ResourceManager.GetObject("表示形式選択", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 貼り付け {
            get {
                object obj = ResourceManager.GetObject("貼り付け", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 鉛筆 {
            get {
                object obj = ResourceManager.GetObject("鉛筆", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 開く {
            get {
                object obj = ResourceManager.GetObject("開く", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 音楽ドキュメント {
            get {
                object obj = ResourceManager.GetObject("音楽ドキュメント", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
