//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTX2WAV.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DTX2WAV.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Overwrite confirmation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string confirmOverwriteCaption {
            get {
                return ResourceManager.GetString("confirmOverwriteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output audio file already exists. Overwrite? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string confirmOverwriteText {
            get {
                return ResourceManager.GetString("confirmOverwriteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed launching DTXMania に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string errFailedLaunchingDTXManiaCaption {
            get {
                return ResourceManager.GetString("errFailedLaunchingDTXManiaCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed launching DTXMania. Can&apos;t record DTX sound. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string errFailedLaunchingDTXManiaText {
            get {
                return ResourceManager.GetString("errFailedLaunchingDTXManiaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error: Unexpected output file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string errIllegalExtentionCaption {
            get {
                return ResourceManager.GetString("errIllegalExtentionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DTX/GDA/G2D file is specified as output file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string errIllegalExtentionText {
            get {
                return ResourceManager.GetString("errIllegalExtentionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error: No DTX file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string errNoDTXFileCaption {
            get {
                return ResourceManager.GetString("errNoDTXFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to load input file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string errNoDTXFileText {
            get {
                return ResourceManager.GetString("errNoDTXFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error: File is not found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string errNoOutFileCaption {
            get {
                return ResourceManager.GetString("errNoOutFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No output file specified. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string errNoOutFileText {
            get {
                return ResourceManager.GetString("errNoOutFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DTX file(*.dtx)|*.dtx|GDA file(*.gda;*.g2d)|*.gda;*.g2d)|All files(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ofdFilter {
            get {
                return ResourceManager.GetString("ofdFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select DTX file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ofdTitle {
            get {
                return ResourceManager.GetString("ofdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All files(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string sfdFilterALL {
            get {
                return ResourceManager.GetString("sfdFilterALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MP3 file(*.mp3)|*.mp3|All files(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string sfdFilterMP3 {
            get {
                return ResourceManager.GetString("sfdFilterMP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OGG file(*.ogg)|*.ogg|All files(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string sfdFilterOGG {
            get {
                return ResourceManager.GetString("sfdFilterOGG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WAV file(*.wav)|*.wav|All files(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string sfdFilterWAV {
            get {
                return ResourceManager.GetString("sfdFilterWAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set ouput file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string sfdTitle {
            get {
                return ResourceManager.GetString("sfdTitle", resourceCulture);
            }
        }
    }
}
