//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTXMania.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DTXMania.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dtx {
            get {
                object obj = ResourceManager.GetObject("dtx", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Play the right cymbal automatically. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgAutoCY {
            get {
                return ResourceManager.GetString("strCfgAutoCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play the hi-hat (closed) automatically. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgAutoHHC {
            get {
                return ResourceManager.GetString("strCfgAutoHHC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play the hi-hat (opened) automatically. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgAutoHHO {
            get {
                return ResourceManager.GetString("strCfgAutoHHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play the left cymbal automatically. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgAutoLCY {
            get {
                return ResourceManager.GetString("strCfgAutoLCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play the ride cymbal automatically. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgAutoRD {
            get {
                return ResourceManager.GetString("strCfgAutoRD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Switch to play the bass automatically. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgBsAllAuto {
            get {
                return ResourceManager.GetString("strCfgBsAllAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Press the bass B lane automatically. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgBsAutoB {
            get {
                return ResourceManager.GetString("strCfgBsAutoB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Press the bass G lane automatically. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgBsAutoG {
            get {
                return ResourceManager.GetString("strCfgBsAutoG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pick the bass automatically. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgBsAutoPick {
            get {
                return ResourceManager.GetString("strCfgBsAutoPick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Press the bass R lane automatically. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgBsAutoR {
            get {
                return ResourceManager.GetString("strCfgBsAutoR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do the bass wailing automatically. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgBsAutoWailing {
            get {
                return ResourceManager.GetString("strCfgBsAutoWailing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Return to the left menu. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgCommon左側メニューに戻ります {
            get {
                return ResourceManager.GetString("strCfgCommon左側メニューに戻ります", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDgbAutoGhost {
            get {
                return ResourceManager.GetString("strCfgDgbAutoGhost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDgbChipSoundMonitor {
            get {
                return ResourceManager.GetString("strCfgDgbChipSoundMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDgbDisplayCombo {
            get {
                return ResourceManager.GetString("strCfgDgbDisplayCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDgbDisplayGraph {
            get {
                return ResourceManager.GetString("strCfgDgbDisplayGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDgbDisplayJudge {
            get {
                return ResourceManager.GetString("strCfgDgbDisplayJudge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDgbHidden {
            get {
                return ResourceManager.GetString("strCfgDgbHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDgbHiddenFrom {
            get {
                return ResourceManager.GetString("strCfgDgbHiddenFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDgbInputAdjust {
            get {
                return ResourceManager.GetString("strCfgDgbInputAdjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDgbInvisible {
            get {
                return ResourceManager.GetString("strCfgDgbInvisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDgbLeft {
            get {
                return ResourceManager.GetString("strCfgDgbLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDgbLight {
            get {
                return ResourceManager.GetString("strCfgDgbLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDgbMinComboDisp {
            get {
                return ResourceManager.GetString("strCfgDgbMinComboDisp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDgbRandom {
            get {
                return ResourceManager.GetString("strCfgDgbRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDgbReverse {
            get {
                return ResourceManager.GetString("strCfgDgbReverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDgbScrollSpeed {
            get {
                return ResourceManager.GetString("strCfgDgbScrollSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDgbSudden {
            get {
                return ResourceManager.GetString("strCfgDgbSudden", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDgbSuddenFrom {
            get {
                return ResourceManager.GetString("strCfgDgbSuddenFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDgbSudHidInv {
            get {
                return ResourceManager.GetString("strCfgDgbSudHidInv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDgbTargetGhost {
            get {
                return ResourceManager.GetString("strCfgDgbTargetGhost", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispBassXBoth {
            get {
                return ResourceManager.GetString("strCfgDispBassXBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispBassXGB {
            get {
                return ResourceManager.GetString("strCfgDispBassXGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispBsComboXBoth {
            get {
                return ResourceManager.GetString("strCfgDispBsComboXBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispBsComboXGB {
            get {
                return ResourceManager.GetString("strCfgDispBsComboXGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispBsComboYBoth {
            get {
                return ResourceManager.GetString("strCfgDispBsComboYBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispBsComboYGB {
            get {
                return ResourceManager.GetString("strCfgDispBsComboYGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispBsJudge {
            get {
                return ResourceManager.GetString("strCfgDispBsJudge", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispBsJudgeLine {
            get {
                return ResourceManager.GetString("strCfgDispBsJudgeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispDebugXBoth {
            get {
                return ResourceManager.GetString("strCfgDispDebugXBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispDebugXDr {
            get {
                return ResourceManager.GetString("strCfgDispDebugXDr", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispDebugXGB {
            get {
                return ResourceManager.GetString("strCfgDispDebugXGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispDebugYBoth {
            get {
                return ResourceManager.GetString("strCfgDispDebugYBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispDebugYDr {
            get {
                return ResourceManager.GetString("strCfgDispDebugYDr", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispDebugYGB {
            get {
                return ResourceManager.GetString("strCfgDispDebugYGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispDrComboXBoth {
            get {
                return ResourceManager.GetString("strCfgDispDrComboXBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispDrComboXDr {
            get {
                return ResourceManager.GetString("strCfgDispDrComboXDr", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispDrComboYBoth {
            get {
                return ResourceManager.GetString("strCfgDispDrComboYBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispDrComboYDr {
            get {
                return ResourceManager.GetString("strCfgDispDrComboYDr", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispDrJudge {
            get {
                return ResourceManager.GetString("strCfgDispDrJudge", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispDrJudgeLine {
            get {
                return ResourceManager.GetString("strCfgDispDrJudgeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispDrumsXBoth {
            get {
                return ResourceManager.GetString("strCfgDispDrumsXBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispDrumsXDr {
            get {
                return ResourceManager.GetString("strCfgDispDrumsXDr", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispGtComboXBoth {
            get {
                return ResourceManager.GetString("strCfgDispGtComboXBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispGtComboXGB {
            get {
                return ResourceManager.GetString("strCfgDispGtComboXGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispGtComboYBoth {
            get {
                return ResourceManager.GetString("strCfgDispGtComboYBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispGtComboYGB {
            get {
                return ResourceManager.GetString("strCfgDispGtComboYGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispGtJudge {
            get {
                return ResourceManager.GetString("strCfgDispGtJudge", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispGtJudgeLine {
            get {
                return ResourceManager.GetString("strCfgDispGtJudgeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispGuitarXBoth {
            get {
                return ResourceManager.GetString("strCfgDispGuitarXBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispGuitarXGB {
            get {
                return ResourceManager.GetString("strCfgDispGuitarXGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispLaneOrderBD {
            get {
                return ResourceManager.GetString("strCfgDispLaneOrderBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispLaneOrderBsB {
            get {
                return ResourceManager.GetString("strCfgDispLaneOrderBsB", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispLaneOrderBsG {
            get {
                return ResourceManager.GetString("strCfgDispLaneOrderBsG", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispLaneOrderBsR {
            get {
                return ResourceManager.GetString("strCfgDispLaneOrderBsR", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispLaneOrderBsW {
            get {
                return ResourceManager.GetString("strCfgDispLaneOrderBsW", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispLaneOrderCY {
            get {
                return ResourceManager.GetString("strCfgDispLaneOrderCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispLaneOrderFT {
            get {
                return ResourceManager.GetString("strCfgDispLaneOrderFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispLaneOrderGtB {
            get {
                return ResourceManager.GetString("strCfgDispLaneOrderGtB", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispLaneOrderGtG {
            get {
                return ResourceManager.GetString("strCfgDispLaneOrderGtG", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispLaneOrderGtR {
            get {
                return ResourceManager.GetString("strCfgDispLaneOrderGtR", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispLaneOrderGtW {
            get {
                return ResourceManager.GetString("strCfgDispLaneOrderGtW", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispLaneOrderHH {
            get {
                return ResourceManager.GetString("strCfgDispLaneOrderHH", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispLaneOrderHT {
            get {
                return ResourceManager.GetString("strCfgDispLaneOrderHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispLaneOrderLC {
            get {
                return ResourceManager.GetString("strCfgDispLaneOrderLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispLaneOrderLT {
            get {
                return ResourceManager.GetString("strCfgDispLaneOrderLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispLaneOrderSD {
            get {
                return ResourceManager.GetString("strCfgDispLaneOrderSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispMovieXBoth {
            get {
                return ResourceManager.GetString("strCfgDispMovieXBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispMovieXDr {
            get {
                return ResourceManager.GetString("strCfgDispMovieXDr", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispMovieXGB {
            get {
                return ResourceManager.GetString("strCfgDispMovieXGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispMovieYBoth {
            get {
                return ResourceManager.GetString("strCfgDispMovieYBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispMovieYDr {
            get {
                return ResourceManager.GetString("strCfgDispMovieYDr", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDispMovieYGB {
            get {
                return ResourceManager.GetString("strCfgDispMovieYGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDrAllAuto {
            get {
                return ResourceManager.GetString("strCfgDrAllAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDrAutoBD {
            get {
                return ResourceManager.GetString("strCfgDrAutoBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDrAutoFT {
            get {
                return ResourceManager.GetString("strCfgDrAutoFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDrAutoHH {
            get {
                return ResourceManager.GetString("strCfgDrAutoHH", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDrAutoHHC {
            get {
                return ResourceManager.GetString("strCfgDrAutoHHC", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDrAutoHHO {
            get {
                return ResourceManager.GetString("strCfgDrAutoHHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDrAutoHT {
            get {
                return ResourceManager.GetString("strCfgDrAutoHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDrAutoLT {
            get {
                return ResourceManager.GetString("strCfgDrAutoLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDrAutoSD {
            get {
                return ResourceManager.GetString("strCfgDrAutoSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDrBDGroup {
            get {
                return ResourceManager.GetString("strCfgDrBDGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDrChipSound {
            get {
                return ResourceManager.GetString("strCfgDrChipSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDrCYGroup {
            get {
                return ResourceManager.GetString("strCfgDrCYGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDrCymbalFree {
            get {
                return ResourceManager.GetString("strCfgDrCymbalFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDrCYPriority {
            get {
                return ResourceManager.GetString("strCfgDrCYPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDrFillin {
            get {
                return ResourceManager.GetString("strCfgDrFillin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDrFTGroup {
            get {
                return ResourceManager.GetString("strCfgDrFTGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDrFTPriority {
            get {
                return ResourceManager.GetString("strCfgDrFTPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDrHHGroup {
            get {
                return ResourceManager.GetString("strCfgDrHHGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDrHHPriority {
            get {
                return ResourceManager.GetString("strCfgDrHHPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgDrTight {
            get {
                return ResourceManager.GetString("strCfgDrTight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgGtAllAuto {
            get {
                return ResourceManager.GetString("strCfgGtAllAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgGtAutoB {
            get {
                return ResourceManager.GetString("strCfgGtAutoB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgGtAutoG {
            get {
                return ResourceManager.GetString("strCfgGtAutoG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgGtAutoPick {
            get {
                return ResourceManager.GetString("strCfgGtAutoPick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgGtAutoR {
            get {
                return ResourceManager.GetString("strCfgGtAutoR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgGtAutoWailing {
            get {
                return ResourceManager.GetString("strCfgGtAutoWailing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgKeyAssignBD {
            get {
                return ResourceManager.GetString("strCfgKeyAssignBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgKeyAssignBsB {
            get {
                return ResourceManager.GetString("strCfgKeyAssignBsB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgKeyAssignBsCancel {
            get {
                return ResourceManager.GetString("strCfgKeyAssignBsCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgKeyAssignBsDecide {
            get {
                return ResourceManager.GetString("strCfgKeyAssignBsDecide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgKeyAssignBsG {
            get {
                return ResourceManager.GetString("strCfgKeyAssignBsG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgKeyAssignBsPick {
            get {
                return ResourceManager.GetString("strCfgKeyAssignBsPick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgKeyAssignBsR {
            get {
                return ResourceManager.GetString("strCfgKeyAssignBsR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgKeyAssignBsWailing {
            get {
                return ResourceManager.GetString("strCfgKeyAssignBsWailing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgKeyAssignCY {
            get {
                return ResourceManager.GetString("strCfgKeyAssignCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgKeyAssignFT {
            get {
                return ResourceManager.GetString("strCfgKeyAssignFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgKeyAssignGtB {
            get {
                return ResourceManager.GetString("strCfgKeyAssignGtB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgKeyAssignGtCancel {
            get {
                return ResourceManager.GetString("strCfgKeyAssignGtCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgKeyAssignGtDecide {
            get {
                return ResourceManager.GetString("strCfgKeyAssignGtDecide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgKeyAssignGtG {
            get {
                return ResourceManager.GetString("strCfgKeyAssignGtG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgKeyAssignGtPick {
            get {
                return ResourceManager.GetString("strCfgKeyAssignGtPick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgKeyAssignGtR {
            get {
                return ResourceManager.GetString("strCfgKeyAssignGtR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgKeyAssignGtWailing {
            get {
                return ResourceManager.GetString("strCfgKeyAssignGtWailing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgKeyAssignHH {
            get {
                return ResourceManager.GetString("strCfgKeyAssignHH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgKeyAssignHHO {
            get {
                return ResourceManager.GetString("strCfgKeyAssignHHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgKeyAssignHP {
            get {
                return ResourceManager.GetString("strCfgKeyAssignHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgKeyAssignHT {
            get {
                return ResourceManager.GetString("strCfgKeyAssignHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgKeyAssignLC {
            get {
                return ResourceManager.GetString("strCfgKeyAssignLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgKeyAssignLT {
            get {
                return ResourceManager.GetString("strCfgKeyAssignLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgKeyAssignRD {
            get {
                return ResourceManager.GetString("strCfgKeyAssignRD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgKeyAssignSD {
            get {
                return ResourceManager.GetString("strCfgKeyAssignSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Capture key assign:\nTo assign key for screen capture.\n(You can assign keyboard only. You can&apos;t use pads to capture screenshot.) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgKeyAssignキャプチャ説明 {
            get {
                return ResourceManager.GetString("strCfgKeyAssignキャプチャ説明", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSts {
            get {
                return ResourceManager.GetString("strCfgSts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSysAdjustWaves {
            get {
                return ResourceManager.GetString("strCfgSysAdjustWaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSysASIODevice {
            get {
                return ResourceManager.GetString("strCfgSysASIODevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSysAudience {
            get {
                return ResourceManager.GetString("strCfgSysAudience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSysAutoResultCapture {
            get {
                return ResourceManager.GetString("strCfgSysAutoResultCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSysAutoVolume {
            get {
                return ResourceManager.GetString("strCfgSysAutoVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSysAVI {
            get {
                return ResourceManager.GetString("strCfgSysAVI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSysBGA {
            get {
                return ResourceManager.GetString("strCfgSysBGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSysBGAAlpha {
            get {
                return ResourceManager.GetString("strCfgSysBGAAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSysBGM {
            get {
                return ResourceManager.GetString("strCfgSysBGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSysBufferingInput {
            get {
                return ResourceManager.GetString("strCfgSysBufferingInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSysChipVolume {
            get {
                return ResourceManager.GetString("strCfgSysChipVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSysDamageLevel {
            get {
                return ResourceManager.GetString("strCfgSysDamageLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSysDark {
            get {
                return ResourceManager.GetString("strCfgSysDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSysDebugInfo {
            get {
                return ResourceManager.GetString("strCfgSysDebugInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSysEnumSongs {
            get {
                return ResourceManager.GetString("strCfgSysEnumSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test highpowerplan に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSysForceHighPowerPlan {
            get {
                return ResourceManager.GetString("strCfgSysForceHighPowerPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSysFullAVI {
            get {
                return ResourceManager.GetString("strCfgSysFullAVI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSysFullScreen {
            get {
                return ResourceManager.GetString("strCfgSysFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSysJudgePriority {
            get {
                return ResourceManager.GetString("strCfgSysJudgePriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSysLog {
            get {
                return ResourceManager.GetString("strCfgSysLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSysMasterVolume {
            get {
                return ResourceManager.GetString("strCfgSysMasterVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSysPlayMode {
            get {
                return ResourceManager.GetString("strCfgSysPlayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSysPlaySpeed {
            get {
                return ResourceManager.GetString("strCfgSysPlaySpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSysPreImageWait {
            get {
                return ResourceManager.GetString("strCfgSysPreImageWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSysPreSoundWait {
            get {
                return ResourceManager.GetString("strCfgSysPreSoundWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSysRandSubBox {
            get {
                return ResourceManager.GetString("strCfgSysRandSubBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSysRisky {
            get {
                return ResourceManager.GetString("strCfgSysRisky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSysSaveScoreIni {
            get {
                return ResourceManager.GetString("strCfgSysSaveScoreIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSysShowLagType {
            get {
                return ResourceManager.GetString("strCfgSysShowLagType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSysSkin {
            get {
                return ResourceManager.GetString("strCfgSysSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSysSoundDeviceType {
            get {
                return ResourceManager.GetString("strCfgSysSoundDeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSysSoundLoadLimiter {
            get {
                return ResourceManager.GetString("strCfgSysSoundLoadLimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSysStageFailed {
            get {
                return ResourceManager.GetString("strCfgSysStageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSysStoic {
            get {
                return ResourceManager.GetString("strCfgSysStoic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSysTimeStretch {
            get {
                return ResourceManager.GetString("strCfgSysTimeStretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSysUseBoxDefSkin {
            get {
                return ResourceManager.GetString("strCfgSysUseBoxDefSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSysUseOSTimer {
            get {
                return ResourceManager.GetString("strCfgSysUseOSTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSysVSync {
            get {
                return ResourceManager.GetString("strCfgSysVSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSysWASAPIBufSize {
            get {
                return ResourceManager.GetString("strCfgSysWASAPIBufSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test WASAPIEventDriven に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strCfgSysWASAPIEventDriven {
            get {
                return ResourceManager.GetString("strCfgSysWASAPIEventDriven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   START に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strTitleStart {
            get {
                return ResourceManager.GetString("strTitleStart", resourceCulture);
            }
        }
    }
}
